# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: detect-private-key
    -   id: fix-encoding-pragma
-   repo: https://github.com/psf/black
    rev: 22.3.0 # Replace by any tag/version: https://github.com/psf/black/tags
    hooks:
    - id: black
      language_version: python # Should be a command that runs python3.6+
-   repo: https://github.com/timothycrosley/isort
    rev: "5.10.1"
    hooks:
      - id: isort
        language_version: python3
        args: ["-m", "VERTICAL_HANGING_INDENT", "--trailing-comma"]
