STATSD_ENABLED = False
STATSD_HOST = "localhost"
STATSD_PORT = 8125
STATSD_LOG_PERIODIC = True
STATSD_LOG_EVERY = 5
STATSD_PREFIX = "scrapy"
STATSD_HANDLER = "scrapy_statsd_extension.handlers.graphite.GraphiteHandler"
STATSD_LOG_ONLY = []
STATSD_IGNORE = []
STATSD_TAGGING = True
STATSD_TAGS = {"spider_name": True}
